### ISSUE TITLE
General: Move to a Task Queue

### ISSUE THREAD

**Issue by jtdroste** [ubnetdef/scoreengine#12]
We should move from a central scoreengine server, to a master issuing tasks, and workers working on said tasks.

This lets us have greater IP diversity.

cc @StephenOrJames

**Comment by StephenOrJames** [comment]
This is in progress, but the design I've been working on allows both a central server and a master-worker model so that the former can be used for simplicity if necessary.

**Comment by jtdroste** [comment]
We should add a [results backend](http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#keeping-results).  Possibly use the existing scoreengine db?

In addition, what about [time limits](http://docs.celeryproject.org/en/latest/userguide/workers.html#time-limits)?  We might need to wrap the task in a try/except block, so it can cleanup.

**Comment by jtdroste** [comment]
Next up, let's talk about how to handle inserting / storing.  Maybe have like two threads?

check thread
* checks all running tasks if they have finished, and insert them into the db
* sleep x seconds

round thread
* start tasks for each team of each service
    * these tasks are the raw scoring.checks.XX methods, with maybe some small wrapper around them
* sleep round_time seconds

**Comment by jtdroste** [comment]
This has pretty much been implemented with the taskqueue branch.

@StephenOrJames care to look over it before merging into master? We also still need to convert the old Master (no taskqueue) to use the new Round system.

**Comment by jtdroste** [comment]
Merged to master.
